name: fanpage
description: A new Flutter project.

publish_to: 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  
  google_sign_in: ^5.1.1
  shared_preferences: ^1.0.0
  random_string: ^1.0.0
  image_picker: ^1.0.0
 
  firebase_storage: ^1.0.0

firebase_core: ^1.6.0
  cloud_firestore: ^2.5.3
 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    flutter_lints: ^1.0.0

flutter:  
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
